### ISSUE TITLE
I am getting the error authentication failed

### ISSUE THREAD

**Issue by squeaky2137** [pushrax/node-rcon#35]
I am getting the error authentication failed. The password is 100% correct I have copy and pasted multiple times and just typed. Any idea the reason for the error?

**Comment by pushrax** [comment]
This may be due to sending a command too early, before the authentication step finishes.

I made a simpler example that shows the correct order of events https://github.com/pushrax/node-rcon/blob/master/examples/basic.js

I also updated the stdio example to queue any commands that were issued before authentication finishes. That approach could be an option, depending on your application.

**Comment by squeaky2137** [comment]
Ah ya i forgot to respond here but that was the issue. I had it in order but it wasnt an async / did add a timeout so it would try sending command before fully authenticatings haha i solved this though but ty for responding :)
